name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        env:
          REPOSITORY_PATH: ${{ vars.REPOSITORY_PATH }}
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
